### ISSUE TITLE
Filter which action will trigger which provider

### ISSUE THREAD

**Issue by izeau** [angulartics/angulartics#415] opened 2015-09-30 12:49 UTC
Currently, every action triggers every registered handler, e.g. an event tracking will dispatch to Google Analytics and Mixpanel at the same time if those two are registered.

I was going to decorate the `$analytics` service to monkey-patch `$analytics.eventTrack`, but then I saw that when plugins register handlers they don’t specify who they are, so it's actually quite difficult to filter them.

My goal is to eventually be able to load a list of events and providers, e.g.

```json
{
  "open menu": ["google-analytics"],
  "add friend": ["google-analytics", "mixpanel"],
  ...
}
```

**Comment by ProLoser** [comment] 2015-10-06 23:38
Duplicate of https://github.com/angulartics/angulartics/issues/237#issuecomment-142823983

I am very interested personally in exploring creating event namespaces. This way you do not have to enumerate each and every event and the service that connects with it, you can 'bucketize' events and even have fallbacks.

**Closed by ProLoser** 2015-10-06 23:38 UTC
